spring:
  application:
    name: "notification"
  #########################
  #       DATABASE
  #########################
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #### FALLBACK
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  profiles:
    active: local

accounts:
  message: "Card server message 1234"

#########################
#       SERVER
#########################
server:
  port: 8082
  url: "http://localhost:${server.port}"
  version: "1.0"

#########################
#       EUREKA
#########################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

#########################
#       ACTUATOR
#########################
management:
  endpoints:
    web:
      exposure:
        include: "*"
        # include: health, info, ... (bu usulda aloxida-aloxida chiqarishimiz mumkin)
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "notification"
    description: "notification microservice card application"
    version: "1.0.0"